---
title: "The new 'ARDL' R package. Part 1: Bounds-test advantages"
subtitle: "Why to use the new 'ARDL' R package"
author: Kleanthis Natsiopoulos
date: '2020-04-13'
slug: ardl-pkg-part1
categories: []
tags:
  - R
  - econometrics
image:
  caption: 'Image credit: [**Nikos Chatsios**](https://www.deviantart.com/favloskyknos)'
  focal_point: 'Center'
summary: "The advantages of using the new 'ARDL' R package for the bounds-test for cointegration."
---

I am glad to anounce that my new [`ARDL`](https://CRAN.R-project.org/package=ARDL) package has been published on CRAN! This is part of my Ph.D. at the University of Thessaly under the supervision of the [Associate Professor Nickolaos Tzeremes](https://sites.google.com/site/tzeremesn/).

The `ARDL` package functionality consists mainly of three things (more to come in future updates):

1. Dynamic time-series regression models (ARDL and ECM)

2. Bounds-test for cointegration ([Pesaran et al. (2001)](https://onlinelibrary.wiley.com/doi/abs/10.1002/jae.616))

3. Long-run multipliers (short-run and interim multipliers are comming in the next update)

The first one provides an easy and straight forward way to construct complex Autoregressive Distributed Lag (ARDL) and Error Correction Models (ECM). But most of all, it ensures the accuracy and the quality of the resulted models! This can be achieved as it is not prompt to user errors and doesn't expect from the user to know the exact technical details of the model specification. The only thing the user has to do is to set the type of the model and the appropriate model specification will be automatically computed.

E.g. an ARDL model can be explicitly described by its order, say ARDL(3,1,3,2). So the user asks for an ARDL(3,1,3,2) without having to know its structure which would be of the following form (assuming a constant and linear trend as an example):

$$y_{t} = c_{0} + c_{1}t + \sum_{i=1}^{3}b_{y,i}y_{t-i} + \sum_{j=1}^{3}\sum_{l=0}^{q_{j}}b_{j,l}x_{j,t-l} + \epsilon_{t}$$

$$where \; q_{1}=1, q_{2}=3, q_{3}=2$$

More about this topic and the usage of multipliers will follow in next posts.

Part 1, focuses on the other main functionality of the package. The bounds-test.

## Bounds-test for cointegration

It refers to the famous test[^1] proposed by [Pesaran, Shin and Smith (2001)](https://onlinelibrary.wiley.com/doi/abs/10.1002/jae.616). 

[^1]: 11664 citations on Google Scholar by the time of this post.

The rising usage of the test and the fact that there was not yet (despite the vast demand of the test) a **complete** and **reliable** package for this purpose in R, led me to create it![^2].

[^2]: Note that there are a few packages (on CRAN or in github repos) that provide the test but as we said... **completeness and reliability of results**!

So let's take a quick look on the advantages of using the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package to perform the bounds-test.

## Advantages

### 1. The reliable underlying models

The main building block to perform the bounds-test is the conditional ECM of the underlying ARDL model, as the test itself is actually a joint wald-test on some parameters of the ECM. So having a correctly specified ARDL model **and** its conditional ECM is essential in order to proceed to the test!

Luckily, this is exactly what the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package does!

### 2. Both the F-test and the t-test are available

The bounds-test consists of two tests, the F-test and the t-test. The t-test is a subset of the F-test and both of them have to be performed in order to have a clear conclusion.

### 3. P-values and critical value bounds

The bounds-test is already available in some commercial software. Although, they only provide the critical value bounds for a specific level of statistical significance, but sadly the usual case is that only the 1%, 5% and 10% levels of significance are available. The [`ARDL`](https://CRAN.R-project.org/package=ARDL) package provides critical value bounds for **any** significance level!

More over, **p-values** are available in the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package!

### 4. Exact sample and asymptotic tests

Again, in comparison with other commercial and non-commercial software that only provide asymptotic results, the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package also provides **exact sample** p-values and critical value bounds! This is useful in cases where we have limited data. The asymptotic results (offered by [Pesaran et al. (2001)](https://onlinelibrary.wiley.com/doi/abs/10.1002/jae.616)) assume that our dataset consists of 1000 observations. The truth is that in economics, social science etc we don't have time-series that long. We usually have much less than this (e.g. series like the GDP is hard to be more than 100 observations long), and in this case the problem is even more severe as the asymptotic results would be very far from the truth.

### 5. Cointegrating equation (long-run relationship)

Also, the user can extract the long-run relationship (cointegrating equation) and examine how this fits the original data and graphically check for a degenerate relationship, that can't be seen using just the test.

## Conclusion

This is just one of the package features and just few of its advantages are mentioned here.

Explore more in the [README](https://github.com/Natsiopoulos/ARDL/blob/master/README.md) file!

Feel free to leave a comment below or contact me via e-mail, [linkedin](www.linkedin.com/in/kleanthis-natsiopoulos) or [twitter](https://twitter.com/klnatsio) to request an extra functionality to be included in the pacakge, report any bug or error, or just express your experience using the package!

If you use [`ARDL`](https://CRAN.R-project.org/package=ARDL) in your publications, please cite as:

Natsiopoulos K, Tzeremes N (2020). *ARDL: ARDL, ECM and Bounds-Test for Cointegration*. Ph.D. thesis, University of Thessaly, Department of Economics. R package version 0.1.0

## Why to use the `ARDL` package in your publications

Probably the most valuable part of the pacakge. The answer is coming soon in a future update! Stay tuned!

## References

Pesaran, M. H., Shin, Y., & Smith, R. J. (2001). Bounds testing approaches to the analysis of level relationships. *Journal of Applied Econometrics*, 16(3), 289-326