theme = "hugo-academic"
baseURL = "https://natsiopoulos.netlify.app/"
languageCode = "en-us"
title = "Kleanthis Natsiopoulos"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]