---
title: '''ARDL'' R package v0.1.1 Part 2: Multipliers'
author: "Kleanthis Natsiopoulos"
date: '2021-01-25'
image:
  caption: 'Image credit: [**Nikos Chatsios**](https://www.instagram.com/favlos_kyknos/)'
  focal_point: Center
slug: ardl-pkg-part2
subtitle: Long, short and interim multipliers
summary: Long, short and interim multipliers in 'ARDL' R package v0.1.1.
tags:
- R
- econometrics
categories: []
---

2021 started with a new version of the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package! My supervisor [Professor Nickolaos Tzeremes](https://sites.google.com/site/tzeremesn/) and myself would like to thank you all for the support and the useful comments towards the improvement of the package.

Since the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package is starting to be the standard for the R community regarding the ARDL modeling and the bounds test for cointegration, we decided to expand its capabilities with new features. We have considered your recommendations and we are planning a series of new releases.

The next versions are going to be released frequently, and they are going to include some minor but very useful features that you have asked for. Also, many of you have asked for more advanced models, so that the package can keep up with the latest developments in the literature. These will be more sparse but major updates.

## `ARDL` version 0.1.1

It starts with version 0.1.1 which adds some extra features in the `multipliers` function. This new release also includes some minor corrections in the documentation.

Now you can use the `multipliers` function to calculate the dynamic effects making use of not only the Long-Run multipliers but also the Short-Run and any Interim multipliers!

This is useful as you can get the instant impact (Short-Run) of a variable change, or the impact in 1, 2 or whatever number of periods ahead you want. And it is as easy as specifying the type (for long or short run) or the number of periods for the interim multipliers. For example:

```{r eval=FALSE, include=TRUE}
# Long-Run multipliers
multipliers(object, type = "lr") # or simply multipliers(object) as it is the default

# Short-Run multipliers
multipliers(object, type = "sr") # equivalent to multipliers(object, type = 0)

# Interim multipliers
multipliers(object, type = 4) # Example for the dynamic effect in 4 periods ahead
```

Where the object can be either an ARDL or an UECM model. We are not getting into technicalities here, so we highly recommend reading the [manual](https://cran.r-project.org/web/packages/ARDL/ARDL.pdf) if you are interested in the underlying mathematics. You will also notice how many quirky calculations you get rid of, including potential mistakes in the process but most importantly, your valuable time!

Also, if you use the [`ARDL`](https://CRAN.R-project.org/package=ARDL) package in your publications, please cite the new version as:
  
Kleanthis Natsiopoulos and Nickolaos Tzeremes (2021). *ARDL: ARDL, ECM and Bounds-Test for Cointegration*. R package version 0.1.1. https://CRAN.R-project.org/package=ARDL

## Be part of the evolution

Keep sending me your valuable suggestions, comments or problems you face using the package. Feel free to contact me via e-mail, [linkedin](www.linkedin.com/in/kleanthis-natsiopoulos) or [twitter](https://twitter.com/klnatsio), or raise an issue in the [GitHub repo](https://github.com/Natsiopoulos/ARDL).